name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Убираем предупреждение про Node.js
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        # Теперь путь верный:
        uses: ArtemSerebrennkov/buildozer-action@v1
        with:
          buildozer_version: stable
          command: buildozer -v android debug
          repository_root: .

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: bin/*.apk
