name: Build APK
on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        # Используем Artemis-Skade, он стабильнее
        uses: Artemis-Skade/buildozer-action@v1
        with:
          buildozer_version: master
          python_version: 3.11
        env:
          # Принудительно задаем пользователя, чтобы избежать ошибки chown
          USER: runner

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-music-player-apk
          path: bin/*.apk
