name: Build Kivy APK
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Buildozer
        # Внимательно: здесь правильное имя репозитория
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          buildozer_version: master
          # Если твой buildozer.spec лежит не в корне, укажи папку ниже:
          workdir: . 
        env:
          # Этот параметр исправляет ошибку "chown: invalid user: ‘user’"
          USER: root

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: music-player-release
          # Путь к готовому APK файлу
          path: bin/*.apk
